### get pedidos
GET http://localhost:3000/pedidos
?cod_entregador=25dc48b9-9e76-413c-a538-830b8651330c

### get pedido
GET http://localhost:3000/pedidos/4de10bfb-11b9-4905-93a1-b9d38d9f6739

### create pedido
POST http://localhost:3000/pedidos
Content-Type: application/json

{
  "name": "Big Macs",
  "description": "Hambúrguer Big Mac do McDonalds do shopping Boulevard",
  "address": "Av Cel. Salustiano de Souza",
  "city": "Aracatu",
  "state": "BA",
  "number": "241",
  "postal_code": "46130000",
  "status_pedido": 1,
  "cod_user": "ef48f058-a31c-4618-a905-dc2235067fee"
}

### update pedido
PATCH http://localhost:3000/pedidos/4de10bfb-11b9-4905-93a1-b9d38d9f6739
Content-Type: application/json

{
  "status_pedido": 1
}

### assign entregador
PATCH http://localhost:3000/pedidos/assign-entregador/7613ad7a-7e64-40ef-b73c-e11932460dc1
Content-Type: application/json

{
  "cod_entregador": "cb063e02-ffea-4aed-a19c-fb0c526f308b"
}