### list entregadores
GET http://localhost:3000/entregadores

### get entregadores
GET http://localhost:3000/entregadores/f799cd65-9e6b-4994-8b10-e0b618b74d77

### create entregadores
POST http://localhost:3000/entregadores
Content-Type: application/json

{
  "name": "Jason Momoa",
  "email": "jason.momoa@mail.com",
  "password": "jason#123",
  "phone": "77912345678",
  "cnh": "12345678",
  "habilitado": true,
  "createdAt": "2024-10-17",
  "updatedAt": "2024-10-17"
}

### update entregadores
PATCH http://localhost:3000/entregadores/f799cd65-9e6b-4994-8b10-e0b618b74d77
Content-Type: application/json

{
  "phone": "77912348765",
  "updatedAt": "2024-10-17"
}

### delete entregadores
DELETE http://localhost:3000/entregadores/7315380d-95db-481a-aacf-970d609c6ea1